version: "3.9"
services:
  dev-db:
    image: mysql:8
    ports:
      - 3306:3306
    environment:
      MYSQL_DATABASE: "${MYSQL_DATABASE}"
      MYSQL_USER: "${MYSQL_USER}"
      MYSQL_PASSWORD: "${MYSQL_PASSWORD}"
      MYSQL_ROOT_PASSWORD: "${MYSQL_ROOT_PASSWORD}"
    networks:
      - drinkapp
networks:
  drinkapp:
